### ISSUE TITLE
how to configure modifiers?

### ISSUE THREAD

**Issue by qianguozheng** [netroby/gohttpproxy#3]
I have successfully run the proxy, but I don't know how to configure the request/response modifiers, I saw the code `configure("/configure", m)`, But when I try http://127.0.0.1:8080/configure, it just not work out.

How could I config these things ? please help me thanks.

**Comment by netroby** [comment]
Sorry , The go httpproxy now does not support any modifiers.

**Comment by qianguozheng** [comment]
I have done that.
